/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectionRouteImport } from './routes/protection'
import { Route as MapRouteImport } from './routes/map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallPersonaIdRouteImport } from './routes/call.$personaId'

const ProtectionRoute = ProtectionRouteImport.update({
  id: '/protection',
  path: '/protection',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallPersonaIdRoute = CallPersonaIdRouteImport.update({
  id: '/call/$personaId',
  path: '/call/$personaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/protection': typeof ProtectionRoute
  '/call/$personaId': typeof CallPersonaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/protection': typeof ProtectionRoute
  '/call/$personaId': typeof CallPersonaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/protection': typeof ProtectionRoute
  '/call/$personaId': typeof CallPersonaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/map' | '/protection' | '/call/$personaId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/map' | '/protection' | '/call/$personaId'
  id: '__root__' | '/' | '/map' | '/protection' | '/call/$personaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  ProtectionRoute: typeof ProtectionRoute
  CallPersonaIdRoute: typeof CallPersonaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/protection': {
      id: '/protection'
      path: '/protection'
      fullPath: '/protection'
      preLoaderRoute: typeof ProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$personaId': {
      id: '/call/$personaId'
      path: '/call/$personaId'
      fullPath: '/call/$personaId'
      preLoaderRoute: typeof CallPersonaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  ProtectionRoute: ProtectionRoute,
  CallPersonaIdRoute: CallPersonaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
